[package]
name = "serde-resp"
version = "0.1.0"
authors = ["DEDZTBH <peiqial@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "^1.0.123"
itoa = "^0.4.7"

[dev-dependencies]
